export const NOTES_REQUEST = 'NOTES_REQUEST';
export const NOTES_REQUEST_SUCCESS = 'NOTES_REQUEST_SUCCESS';
export const ARCHIVE_REQUEST = 'ARCHIVE_REQUEST';
export const ARCHIVE_REQUEST_SUCCESS = 'ARCHIVE_REQUEST_SUCCESS';
export const ARCHIVE_NOTE_REQUEST = 'ARCHIVE_NOTE_REQUEST';
export const ARCHIVE_NOTE_REQUEST_SUCCESS = 'ARCHIVE_NOTE_REQUEST_SUCCESS';
export const TOGGLE_COLOR = 'TOGGLE_COLOR';
